
name = "nanonux-website"
compatibility_date = "2026-01-20"

# Configure Cloudflare Pages build output directory for Next-on-Pages
# Cloudflare's Next.js adapter emits static files to '/.vercel/output/static'
pages_build_output_dir = "/.vercel/output/static"


